"""initial

Revision ID: 72b8f93a2bfd
Revises: 
Create Date: 2026-05-28 17:43:16.866180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b8f93a2bfd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monuments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cover_monument_id', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monument_translations',
    sa.Column('monument_id', sa.String(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('field_value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monument_id'], ['monuments.id'], ),
    sa.PrimaryKeyConstraint('monument_id', 'lang', 'field_key')
    )
    op.create_table('route_stops',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('monument_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monument_id'], ['monuments.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('route_id', 'monument_id')
    )
    op.create_table('route_translations',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('route_id', 'lang')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_translations')
    op.drop_table('route_stops')
    op.drop_table('monument_translations')
    op.drop_table('routes')
    op.drop_table('monuments')
    # ### end Alembic commands ###
